name: Setup macOS dependencies

inputs:
  build-type:
    description: Type for the build
    required: true
    default: Debug

runs:
  using: composite

  steps:
    - name: Install dependencies
      shell: bash
      run: |
        brew update
        brew install ninja extra-cmake-modules temurin@17 autoconf pkg-config \
        gpgme qgpgme-qt6

    - name: Set JAVA_HOME
      shell: bash
      run: |
        echo "JAVA_HOME=$(/usr/libexec/java_home -v 17)" >> "$GITHUB_ENV"
