name: "CNG: Build Images"

on:
  workflow_call:
    inputs:
      gitlab-version:
        type: string
        default: "master"
      image-tag:
        type: string
        default: ""
      cng-ref:
        type: string
        default: "master"
      cng-repository:
        type: string
        default: ""
      gitaly-version:
        type: string
        default: ""
      gitlab-shell-version:
        type: string
        default: ""
      gitlab-pages-version:
        type: string
        default: ""
      gitlab-kas-version:
        type: string
        default: ""
      gitlab-elasticsearch-indexer-version:
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      gitlab-version:
        type: string
        default: "master"
      image-tag:
        type: string
        default: ""
      cng-ref:
        type: string
        default: "master"
      cng-repository:
        type: string
        default: ""

permissions: {}

jobs:
  phase-zero:
    name: "phase-zero: ${{ matrix.image }}"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image: [gitlab-go, gitlab-rust]
    steps:
      - uses: Project-Tick-Infrastructure/checkout@v5
        with:
          source-repository: ${{ inputs.cng-repository != '' && inputs.cng-repository || 'https://git.projecttick.org/project-tick/uppfinna/cng' }}
          ref: ${{ inputs.cng-ref || 'master' }}
          submodules: true
      - uses: Project-Tick/Project-Tick/.github/actions/uppfinna-cng-image@master
        with:
          image: ${{ matrix.image }}
          gitlab-version: ${{ inputs.gitlab-version }}
          image-tag: ${{ inputs.image-tag }}
          gitaly-version: ${{ inputs.gitaly-version }}
          gitlab-shell-version: ${{ inputs.gitlab-shell-version }}
          gitlab-pages-version: ${{ inputs.gitlab-pages-version }}
          gitlab-kas-version: ${{ inputs.gitlab-kas-version }}
          gitlab-elasticsearch-indexer-version: ${{ inputs.gitlab-elasticsearch-indexer-version }}
          registry-user: ${{ secrets.CNG_REGISTRY_USER }}
          registry-password: ${{ secrets.CNG_REGISTRY_PASSWORD }}
          fetch-artifacts-pat: ${{ secrets.CNG_FETCH_ARTIFACTS_PAT }}
          ci-registry: ${{ vars.CNG_REGISTRY || 'registry.projecttick.org' }}
          ci-registry-image: ${{ vars.CNG_REGISTRY_IMAGE || 'registry.projecttick.org/project-tick/cng' }}
          gitlab-namespace: ${{ vars.CNG_GITLAB_NAMESPACE || 'project-tick' }}
          ce-project: ${{ vars.CNG_CE_PROJECT || 'gitlab' }}
          ci-api-v4-url: ${{ vars.CNG_API_V4_URL || 'https://git.projecttick.org/api/v4' }}
          ci-server-fqdn: ${{ vars.CNG_SERVER_FQDN || 'git.projecttick.org' }}
          gitaly-git-repo-url: ${{ vars.CNG_GITALY_GIT_REPO_URL || 'https://gitlab.com/gitlab-org/gitaly.git' }}
          assets-image-registry-prefix: ${{ vars.CNG_ASSETS_IMAGE_REGISTRY_PREFIX || 'registry.gitlab.com/gitlab-org' }}

  phase-one:
    name: "phase-one: ${{ matrix.image }}"
    needs: phase-zero
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image: [gitlab-logger, gitlab-gomplate, gitlab-graphicsmagick, gitlab-python, postgresql, cfssl-self-sign, kubectl]
    steps:
      - uses: Project-Tick-Infrastructure/checkout@v5
        with:
          source-repository: ${{ inputs.cng-repository != '' && inputs.cng-repository || 'https://git.projecttick.org/project-tick/uppfinna/cng' }}
          ref: ${{ inputs.cng-ref || 'master' }}
          submodules: true
      - uses: Project-Tick/Project-Tick/.github/actions/uppfinna-cng-image@master
        with:
          image: ${{ matrix.image }}
          gitlab-version: ${{ inputs.gitlab-version }}
          image-tag: ${{ inputs.image-tag }}
          gitaly-version: ${{ inputs.gitaly-version }}
          gitlab-shell-version: ${{ inputs.gitlab-shell-version }}
          gitlab-pages-version: ${{ inputs.gitlab-pages-version }}
          gitlab-kas-version: ${{ inputs.gitlab-kas-version }}
          gitlab-elasticsearch-indexer-version: ${{ inputs.gitlab-elasticsearch-indexer-version }}
          registry-user: ${{ secrets.CNG_REGISTRY_USER }}
          registry-password: ${{ secrets.CNG_REGISTRY_PASSWORD }}
          fetch-artifacts-pat: ${{ secrets.CNG_FETCH_ARTIFACTS_PAT }}
          ci-registry: ${{ vars.CNG_REGISTRY || 'registry.projecttick.org' }}
          ci-registry-image: ${{ vars.CNG_REGISTRY_IMAGE || 'registry.projecttick.org/project-tick/cng' }}
          gitlab-namespace: ${{ vars.CNG_GITLAB_NAMESPACE || 'project-tick' }}
          ce-project: ${{ vars.CNG_CE_PROJECT || 'gitlab' }}
          ci-api-v4-url: ${{ vars.CNG_API_V4_URL || 'https://git.projecttick.org/api/v4' }}
          ci-server-fqdn: ${{ vars.CNG_SERVER_FQDN || 'git.projecttick.org' }}
          gitaly-git-repo-url: ${{ vars.CNG_GITALY_GIT_REPO_URL || 'https://gitlab.com/gitlab-org/gitaly.git' }}
          assets-image-registry-prefix: ${{ vars.CNG_ASSETS_IMAGE_REGISTRY_PREFIX || 'registry.gitlab.com/gitlab-org' }}

  phase-two:
    name: "phase-two: gitlab-base"
    needs: phase-one
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: Project-Tick-Infrastructure/checkout@v5
        with:
          source-repository: ${{ inputs.cng-repository != '' && inputs.cng-repository || 'https://git.projecttick.org/project-tick/uppfinna/cng' }}
          ref: ${{ inputs.cng-ref || 'master' }}
          submodules: true
      - uses: Project-Tick/Project-Tick/.github/actions/uppfinna-cng-image@master
        with:
          image: gitlab-base
          gitlab-version: ${{ inputs.gitlab-version }}
          image-tag: ${{ inputs.image-tag }}
          registry-user: ${{ secrets.CNG_REGISTRY_USER }}
          registry-password: ${{ secrets.CNG_REGISTRY_PASSWORD }}
          fetch-artifacts-pat: ${{ secrets.CNG_FETCH_ARTIFACTS_PAT }}
          ci-registry: ${{ vars.CNG_REGISTRY || 'registry.projecttick.org' }}
          ci-registry-image: ${{ vars.CNG_REGISTRY_IMAGE || 'registry.projecttick.org/project-tick/cng' }}
          gitlab-namespace: ${{ vars.CNG_GITLAB_NAMESPACE || 'project-tick' }}
          ce-project: ${{ vars.CNG_CE_PROJECT || 'gitlab' }}
          ci-api-v4-url: ${{ vars.CNG_API_V4_URL || 'https://git.projecttick.org/api/v4' }}
          ci-server-fqdn: ${{ vars.CNG_SERVER_FQDN || 'git.projecttick.org' }}
          gitaly-git-repo-url: ${{ vars.CNG_GITALY_GIT_REPO_URL || 'https://gitlab.com/gitlab-org/gitaly.git' }}
          assets-image-registry-prefix: ${{ vars.CNG_ASSETS_IMAGE_REGISTRY_PREFIX || 'registry.gitlab.com/gitlab-org' }}

  phase-three:
    name: "phase-three: ${{ matrix.image }}"
    needs: phase-two
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image: [certificates, gitlab-exiftool, gitlab-cosign, gitlab-ruby]
    steps:
      - uses: Project-Tick-Infrastructure/checkout@v5
        with:
          source-repository: ${{ inputs.cng-repository != '' && inputs.cng-repository || 'https://git.projecttick.org/project-tick/uppfinna/cng' }}
          ref: ${{ inputs.cng-ref || 'master' }}
          submodules: true
      - uses: Project-Tick/Project-Tick/.github/actions/uppfinna-cng-image@master
        with:
          image: ${{ matrix.image }}
          gitlab-version: ${{ inputs.gitlab-version }}
          image-tag: ${{ inputs.image-tag }}
          registry-user: ${{ secrets.CNG_REGISTRY_USER }}
          registry-password: ${{ secrets.CNG_REGISTRY_PASSWORD }}
          fetch-artifacts-pat: ${{ secrets.CNG_FETCH_ARTIFACTS_PAT }}
          ci-registry: ${{ vars.CNG_REGISTRY || 'registry.projecttick.org' }}
          ci-registry-image: ${{ vars.CNG_REGISTRY_IMAGE || 'registry.projecttick.org/project-tick/cng' }}
          gitlab-namespace: ${{ vars.CNG_GITLAB_NAMESPACE || 'project-tick' }}
          ce-project: ${{ vars.CNG_CE_PROJECT || 'gitlab' }}
          ci-api-v4-url: ${{ vars.CNG_API_V4_URL || 'https://git.projecttick.org/api/v4' }}
          ci-server-fqdn: ${{ vars.CNG_SERVER_FQDN || 'git.projecttick.org' }}
          gitaly-git-repo-url: ${{ vars.CNG_GITALY_GIT_REPO_URL || 'https://gitlab.com/gitlab-org/gitaly.git' }}
          assets-image-registry-prefix: ${{ vars.CNG_ASSETS_IMAGE_REGISTRY_PREFIX || 'registry.gitlab.com/gitlab-org' }}

  phase-four:
    name: "phase-four: ${{ matrix.image }}"
    needs: phase-three
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image: [gitlab-exporter, gitlab-mailroom, gitaly, gitlab-container-registry, gitlab-kas, gitlab-pages, gitlab-shell]
    steps:
      - uses: Project-Tick-Infrastructure/checkout@v5
        with:
          source-repository: ${{ inputs.cng-repository != '' && inputs.cng-repository || 'https://git.projecttick.org/project-tick/uppfinna/cng' }}
          ref: ${{ inputs.cng-ref || 'master' }}
          submodules: true
      - uses: Project-Tick/Project-Tick/.github/actions/uppfinna-cng-image@master
        with:
          image: ${{ matrix.image }}
          gitlab-version: ${{ inputs.gitlab-version }}
          image-tag: ${{ inputs.image-tag }}
          gitaly-version: ${{ inputs.gitaly-version }}
          gitlab-shell-version: ${{ inputs.gitlab-shell-version }}
          gitlab-pages-version: ${{ inputs.gitlab-pages-version }}
          gitlab-kas-version: ${{ inputs.gitlab-kas-version }}
          gitlab-elasticsearch-indexer-version: ${{ inputs.gitlab-elasticsearch-indexer-version }}
          registry-user: ${{ secrets.CNG_REGISTRY_USER }}
          registry-password: ${{ secrets.CNG_REGISTRY_PASSWORD }}
          fetch-artifacts-pat: ${{ secrets.CNG_FETCH_ARTIFACTS_PAT }}
          ci-registry: ${{ vars.CNG_REGISTRY || 'registry.projecttick.org' }}
          ci-registry-image: ${{ vars.CNG_REGISTRY_IMAGE || 'registry.projecttick.org/project-tick/cng' }}
          gitlab-namespace: ${{ vars.CNG_GITLAB_NAMESPACE || 'project-tick' }}
          ce-project: ${{ vars.CNG_CE_PROJECT || 'gitlab' }}
          ci-api-v4-url: ${{ vars.CNG_API_V4_URL || 'https://git.projecttick.org/api/v4' }}
          ci-server-fqdn: ${{ vars.CNG_SERVER_FQDN || 'git.projecttick.org' }}
          gitaly-git-repo-url: ${{ vars.CNG_GITALY_GIT_REPO_URL || 'https://gitlab.com/gitlab-org/gitaly.git' }}
          assets-image-registry-prefix: ${{ vars.CNG_ASSETS_IMAGE_REGISTRY_PREFIX || 'registry.gitlab.com/gitlab-org' }}

  phase-five:
    name: "phase-five: gitlab-rails-ce"
    needs: phase-four
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: Project-Tick-Infrastructure/checkout@v5
        with:
          source-repository: ${{ inputs.cng-repository != '' && inputs.cng-repository || 'https://git.projecttick.org/project-tick/uppfinna/cng' }}
          ref: ${{ inputs.cng-ref || 'master' }}
          submodules: true
      - uses: Project-Tick/Project-Tick/.github/actions/uppfinna-cng-image@master
        with:
          image: gitlab-rails-ce
          gitlab-version: ${{ inputs.gitlab-version }}
          image-tag: ${{ inputs.image-tag }}
          registry-user: ${{ secrets.CNG_REGISTRY_USER }}
          registry-password: ${{ secrets.CNG_REGISTRY_PASSWORD }}
          fetch-artifacts-pat: ${{ secrets.CNG_FETCH_ARTIFACTS_PAT }}
          ci-registry: ${{ vars.CNG_REGISTRY || 'registry.projecttick.org' }}
          ci-registry-image: ${{ vars.CNG_REGISTRY_IMAGE || 'registry.projecttick.org/project-tick/cng' }}
          gitlab-namespace: ${{ vars.CNG_GITLAB_NAMESPACE || 'project-tick' }}
          ce-project: ${{ vars.CNG_CE_PROJECT || 'gitlab' }}
          ci-api-v4-url: ${{ vars.CNG_API_V4_URL || 'https://git.projecttick.org/api/v4' }}
          ci-server-fqdn: ${{ vars.CNG_SERVER_FQDN || 'git.projecttick.org' }}
          gitaly-git-repo-url: ${{ vars.CNG_GITALY_GIT_REPO_URL || 'https://gitlab.com/gitlab-org/gitaly.git' }}
          assets-image-registry-prefix: ${{ vars.CNG_ASSETS_IMAGE_REGISTRY_PREFIX || 'registry.gitlab.com/gitlab-org' }}

  phase-six:
    name: "phase-six: ${{ matrix.image }}"
    needs: phase-five
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image: [gitlab-sidekiq-ce, gitlab-toolbox-ce, gitlab-webservice-ce, gitlab-workhorse-ce]
    steps:
      - uses: Project-Tick-Infrastructure/checkout@v5
        with:
          source-repository: ${{ inputs.cng-repository != '' && inputs.cng-repository || 'https://git.projecttick.org/project-tick/uppfinna/cng' }}
          ref: ${{ inputs.cng-ref || 'master' }}
          submodules: true
      - uses: Project-Tick/Project-Tick/.github/actions/uppfinna-cng-image@master
        with:
          image: ${{ matrix.image }}
          gitlab-version: ${{ inputs.gitlab-version }}
          image-tag: ${{ inputs.image-tag }}
          registry-user: ${{ secrets.CNG_REGISTRY_USER }}
          registry-password: ${{ secrets.CNG_REGISTRY_PASSWORD }}
          fetch-artifacts-pat: ${{ secrets.CNG_FETCH_ARTIFACTS_PAT }}
          ci-registry: ${{ vars.CNG_REGISTRY || 'registry.projecttick.org' }}
          ci-registry-image: ${{ vars.CNG_REGISTRY_IMAGE || 'registry.projecttick.org/project-tick/cng' }}
          gitlab-namespace: ${{ vars.CNG_GITLAB_NAMESPACE || 'project-tick' }}
          ce-project: ${{ vars.CNG_CE_PROJECT || 'gitlab' }}
          ci-api-v4-url: ${{ vars.CNG_API_V4_URL || 'https://git.projecttick.org/api/v4' }}
          ci-server-fqdn: ${{ vars.CNG_SERVER_FQDN || 'git.projecttick.org' }}
          gitaly-git-repo-url: ${{ vars.CNG_GITALY_GIT_REPO_URL || 'https://gitlab.com/gitlab-org/gitaly.git' }}
          assets-image-registry-prefix: ${{ vars.CNG_ASSETS_IMAGE_REGISTRY_PREFIX || 'registry.gitlab.com/gitlab-org' }}
